apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: registry.gengbo.top/home:v20251205001
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 12445

---
apiVersion: v1
kind: Service
metadata:
  name: home
  namespace: dev
spec:
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 12445

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home
  namespace: dev
#  annotations:
#    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - gengbo.top
    secretName: gengbo.top-tls
  rules:
  - host: gengbo.top
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: home
            port:
              number: 80

